FactoryBot.define do
  factory :client do
    sequence(:name) { |n| "Client #{n}" }
    address { "123 Business Street\nNew York, NY 10001\nUSA" }
    email { "contact@example.com" }
    contact_person { "John Doe" }
    vat_id { "US123456789" }
    company_registration { "REG-12345" }
    bank_details { "Bank: First National\nAccount: 1234567890\nRouting: 021000021" }
    payment_terms { "Net 30 days" }
    hourly_rate { 120.00 }
    currency { "EUR" }
    # share_token is auto-generated by the model, so we don't set it here

    trait :usd do
      currency { "USD" }
    end

    trait :gbp do
      currency { "GBP" }
    end

    trait :with_custom_rate do
      transient do
        rate { 150.00 }
      end

      hourly_rate { rate }
    end

    trait :minimal do
      name { "Minimal Client" }
      address { nil }
      email { nil }
      contact_person { nil }
      vat_id { nil }
      company_registration { nil }
      bank_details { nil }
      payment_terms { nil }
      hourly_rate { nil }
      currency { nil }
    end
  end
end
